<a href="https://colab.research.google.com/github/Tanishka002/Chocolate-cake-Recipe/blob/main/Copy_of_PRO_C125_Project_Boilerplate_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Archery-Target** is a game in which the players shoot sharp-pointed arrows at a round target having 10 rings.

<img src="https://s3-whjr-curriculum-uploads.whjr.online/4de9132a-c71d-42ce-9099-3293e8805fd9.jpg"> 

## RL Problem to Solve
Hit the center of the target with maximum reward

<img src="https://s3-whjr-curriculum-uploads.whjr.online/40656a8c-14e2-4dd7-9f9e-4c17669b9182.png" width=300>


Number of **State**: ?

Number of **Actions**: ?



## Rewards

In [1]:
#import required libraries
import numpy as np
import random


## Reward Matrix
Reward Matrix represents states as rows and actions as columns with respective awards values assigned for a given state and action pair.

In [2]:
#Create reward matrix
rewards = np.array([
 [0,1,2,5,10]
])



In [3]:
def set_initial_state():
  return np.random.randint(0,5)

In [4]:
set_initial_state()

4

## Take Action Randomly

In [5]:
#Define a function shoot() for taking random action
 
def shoot(current_state,reward_matrix):
  available_action=[]
  print("reward_matrix","\n",reward_matrix)
  for action in enumerate(reward_matrix[current_state]):
    if action[1]!=-1:
      available_action.append(action[0])
      choose_action=random.choice(available_action)
      print("random choice of action from",available_action,"is",choose_action)
      return choose_action
 

In [6]:
current_state = 0
action=shoot(current_state,rewards)
print(action)

reward_matrix 
 [[ 0  1  2  5 10]]
random choice of action from [0] is 0
0


In [7]:
q_matrix=np.zeros([1,5])
print(q_matrix)

[[0. 0. 0. 0. 0.]]


In [13]:
gamma=0.8
def take_action(reward_matrix):
  action=shoot(current_state,reward_matrix)
  print(action)
  reward=reward_matrix[current_state,action]
  print(reward)
  q_sa_value=max(q_matrix[action,])
  print(q_sa_value)

  q_current_state=reward+(gamma*q_sa_value)
  print(q_current_state)

  q_matrix[current_state,action]=q_current_state
  print("q_matrix","\n",q_matrix)
  return action,reward


In [22]:
take_action(rewards)

reward_matrix 
 [[ 0  1  2  5 10]]
random choice of action from [0] is 0
0
0
0.0
0.0
q_matrix 
 [[0. 0. 0. 0. 0.]]


(0, 0)